name: Import Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: CPM
            dir: cmake_cpm
            setup_bazel: false
          - name: Install and Find Package
            dir: cmake_install_find_package
            setup_bazel: false
          - name: Bazel bzlmod
            dir: bazel_bzlmod
            setup_bazel: true
          - name: Bazel Workspace
            dir: bazel_workspace
            setup_bazel: true

    name: Import test - ${{ matrix.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up GITHUB_TOKEN
        run: |
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Setup Bazel environment
        if: matrix.setup_bazel
        uses: bazel-contrib/setup-bazel@0.8.1

      - name: Run test
        run: |
          cd test/import_test/${{ matrix.dir }}
          ./build_ci.sh
